#!/bin/bash

# Zero Trust VPN Infrastructure - Security Audit Script
# This script performs comprehensive security audits of the Zero Trust VPN infrastructure
# including certificate validation, access control verification, and security compliance checks

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"
CONFIG_DIR="$PROJECT_ROOT/config-examples"
CERT_DIR="$PROJECT_ROOT/certificates"
LOG_DIR="/var/log/zero-trust-vpn"
AUDIT_REPORT_DIR="$PROJECT_ROOT/audit-reports"

# Audit configuration
CERT_EXPIRY_WARNING_DAYS=30
MAX_FAILED_LOGINS=5
AUDIT_TIMESTAMP=$(date +%Y%m%d_%H%M%S)
REPORT_FILE="$AUDIT_REPORT_DIR/security_audit_$AUDIT_TIMESTAMP.txt"

log() {
    echo -e "${GREEN}[$(date +'%Y-%m-%d %H:%M:%S')] $1${NC}"
}

warn() {
    echo -e "${YELLOW}[$(date +'%Y-%m-%d %H:%M:%S')] WARNING: $1${NC}"
}

error() {
    echo -e "${RED}[$(date +'%Y-%m-%d %H:%M:%S')] ERROR: $1${NC}"
}

info() {
    echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')] INFO: $1${NC}"
}

critical() {
    echo -e "${PURPLE}[$(date +'%Y-%m-%d %H:%M:%S')] CRITICAL: $1${NC}"
}

# Display usage information
usage() {
    cat << EOF
Usage: $0 [OPTIONS]

Zero Trust VPN Security Audit Script

OPTIONS:
    --full                  Perform full comprehensive audit
    --quick                 Perform quick security check
    --certificates          Audit certificate status only
    --access-control        Audit access control policies only
    --network               Audit network configuration only
    --compliance            Check compliance with security standards
    --report-only           Generate report without console output
    --output FILE           Specify custom output file
    -v, --verbose           Enable verbose output
    -h, --help              Show this help message

AUDIT CATEGORIES:
    - Certificate Management
    - Access Control Policies
    - Network Security Configuration
    - User and Device Management
    - Log Analysis and Monitoring
    - Compliance Verification

EXAMPLES:
    $0 --full                           # Complete security audit
    $0 --quick                          # Quick security check
    $0 --certificates --verbose         # Detailed certificate audit
    $0 --compliance --output report.txt # Compliance check with custom output

EOF
}

# Parse command line arguments
parse_args() {
    AUDIT_TYPE="full"
    VERBOSE=false
    REPORT_ONLY=false
    CUSTOM_OUTPUT=""

    while [[ $# -gt 0 ]]; do
        case $1 in
            --full)
                AUDIT_TYPE="full"
                shift
                ;;
            --quick)
                AUDIT_TYPE="quick"
                shift
                ;;
            --certificates)
                AUDIT_TYPE="certificates"
                shift
                ;;
            --access-control)
                AUDIT_TYPE="access-control"
                shift
                ;;
            --network)
                AUDIT_TYPE="network"
                shift
                ;;
            --compliance)
                AUDIT_TYPE="compliance"
                shift
                ;;
            --report-only)
                REPORT_ONLY=true
                shift
                ;;
            --output)
                CUSTOM_OUTPUT="$2"
                shift 2
                ;;
            -v|--verbose)
                VERBOSE=true
                shift
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            *)
                error "Unknown option: $1"
                exit 1
                ;;
        esac
    done

    # Set custom output file if specified
    if [[ -n "$CUSTOM_OUTPUT" ]]; then
        REPORT_FILE="$CUSTOM_OUTPUT"
    fi
}

# Initialize audit environment
init_audit() {
    log "Initializing security audit..."

    # Create necessary directories
    mkdir -p "$AUDIT_REPORT_DIR" "$LOG_DIR"

    # Initialize report file
    cat > "$REPORT_FILE" << EOF
Zero Trust VPN Infrastructure Security Audit Report
===================================================

Audit Date: $(date)
Audit Type: $AUDIT_TYPE
Generated by: $(whoami)@$(hostname)

EOF

    # Check prerequisites
    local required_commands=("openssl" "wg" "systemctl" "ss" "iptables")
    for cmd in "${required_commands[@]}"; do
        if ! command -v "$cmd" &> /dev/null; then
            error "Required command not found: $cmd"
            exit 1
        fi
    done
}

# Write to report file
write_report() {
    echo "$1" >> "$REPORT_FILE"
    if [[ "$REPORT_ONLY" != "true" ]]; then
        echo "$1"
    fi
}

# Audit certificate management
audit_certificates() {
    write_report ""
    write_report "Certificate Management Audit"
    write_report "============================"

    local cert_issues=0

    # Check CA certificate
    if [[ -f "$CERT_DIR/ca/ca.crt" ]]; then
        local ca_expiry=$(openssl x509 -in "$CERT_DIR/ca/ca.crt" -noout -enddate | cut -d= -f2)
        local ca_days_left=$(( ($(date -d "$ca_expiry" +%s) - $(date +%s)) / 86400 ))
        
        if [[ $ca_days_left -lt $CERT_EXPIRY_WARNING_DAYS ]]; then
            write_report "⚠️  CA Certificate expires in $ca_days_left days ($ca_expiry)"
            ((cert_issues++))
        else
            write_report "✅ CA Certificate valid for $ca_days_left days"
        fi
    else
        write_report "❌ CA Certificate not found"
        ((cert_issues++))
    fi

    # Check server certificate
    if [[ -f "$CERT_DIR/server/server.crt" ]]; then
        local server_expiry=$(openssl x509 -in "$CERT_DIR/server/server.crt" -noout -enddate | cut -d= -f2)
        local server_days_left=$(( ($(date -d "$server_expiry" +%s) - $(date +%s)) / 86400 ))
        
        if [[ $server_days_left -lt $CERT_EXPIRY_WARNING_DAYS ]]; then
            write_report "⚠️  Server Certificate expires in $server_days_left days ($server_expiry)"
            ((cert_issues++))
        else
            write_report "✅ Server Certificate valid for $server_days_left days"
        fi
    else
        write_report "❌ Server Certificate not found"
        ((cert_issues++))
    fi

    # Check client certificates
    local client_cert_count=0
    local expiring_client_certs=0

    if [[ -d "$CERT_DIR/clients" ]]; then
        for client_dir in "$CERT_DIR/clients"/*; do
            if [[ -d "$client_dir" && -f "$client_dir/client.crt" ]]; then
                ((client_cert_count++))
                local client_name=$(basename "$client_dir")
                local client_expiry=$(openssl x509 -in "$client_dir/client.crt" -noout -enddate | cut -d= -f2)
                local client_days_left=$(( ($(date -d "$client_expiry" +%s) - $(date +%s)) / 86400 ))
                
                if [[ $client_days_left -lt $CERT_EXPIRY_WARNING_DAYS ]]; then
                    write_report "⚠️  Client Certificate '$client_name' expires in $client_days_left days"
                    ((expiring_client_certs++))
                elif [[ "$VERBOSE" == "true" ]]; then
                    write_report "✅ Client Certificate '$client_name' valid for $client_days_left days"
                fi
            fi
        done
    fi

    write_report ""
    write_report "Certificate Summary:"
    write_report "- Total client certificates: $client_cert_count"
    write_report "- Expiring client certificates: $expiring_client_certs"
    write_report "- Total certificate issues: $cert_issues"

    return $cert_issues
}

# Audit access control policies
audit_access_control() {
    write_report ""
    write_report "Access Control Policy Audit"
    write_report "==========================="

    local policy_issues=0

    # Check Authelia configuration
    local authelia_config="$CONFIG_DIR/authelia/configuration.yml"
    if [[ -f "$authelia_config" ]]; then
        write_report "✅ Authelia configuration file found"
        
        # Check for secure session configuration
        if grep -q "secure: true" "$authelia_config"; then
            write_report "✅ Secure session cookies enabled"
        else
            write_report "⚠️  Secure session cookies not explicitly enabled"
            ((policy_issues++))
        fi

        # Check for proper domain configuration
        if grep -q "domain:" "$authelia_config"; then
            write_report "✅ Domain configuration present"
        else
            write_report "❌ Domain configuration missing"
            ((policy_issues++))
        fi
    else
        write_report "❌ Authelia configuration file not found"
        ((policy_issues++))
    fi

    # Check access control rules
    local access_control_file="$CONFIG_DIR/authelia/access-control.yml"
    if [[ -f "$access_control_file" ]]; then
        write_report "✅ Access control rules file found"
        
        # Count rules
        local rule_count=$(yq eval '.access_control.rules | length' "$access_control_file" 2>/dev/null || echo "0")
        write_report "📋 Number of access control rules: $rule_count"
        
        if [[ $rule_count -eq 0 ]]; then
            write_report "⚠️  No access control rules defined"
            ((policy_issues++))
        fi
    else
        write_report "❌ Access control rules file not found"
        ((policy_issues++))
    fi

    # Check user database
    local users_db="$CONFIG_DIR/authelia/users_database.yml"
    if [[ -f "$users_db" ]]; then
        local user_count=$(yq eval '.users | length' "$users_db" 2>/dev/null || echo "0")
        write_report "👥 Number of users in database: $user_count"
        
        # Check for default passwords
        if grep -q "password.*password" "$users_db" 2>/dev/null; then
            write_report "❌ Default passwords detected in user database"
            ((policy_issues++))
        else
            write_report "✅ No obvious default passwords found"
        fi
    else
        write_report "❌ User database file not found"
        ((policy_issues++))
    fi

    write_report ""
    write_report "Access Control Summary:"
    write_report "- Total policy issues: $policy_issues"

    return $policy_issues
}

# Audit network security configuration
audit_network() {
    write_report ""
    write_report "Network Security Configuration Audit"
    write_report "===================================="

    local network_issues=0

    # Check WireGuard service status
    if systemctl is-active --quiet wg-quick@wg0; then
        write_report "✅ WireGuard service is running"
        
        # Check WireGuard interface
        if wg show wg0 &>/dev/null; then
            local peer_count=$(wg show wg0 peers | wc -l)
            write_report "🔗 Active WireGuard peers: $peer_count"
        else
            write_report "❌ WireGuard interface not accessible"
            ((network_issues++))
        fi
    else
        write_report "❌ WireGuard service is not running"
        ((network_issues++))
    fi

    # Check firewall status
    if systemctl is-active --quiet ufw; then
        write_report "✅ UFW firewall is active"
    elif systemctl is-active --quiet iptables; then
        write_report "✅ iptables service is active"
    else
        write_report "⚠️  No active firewall service detected"
        ((network_issues++))
    fi

    # Check for open ports
    local open_ports=$(ss -tuln | grep LISTEN | wc -l)
    write_report "🔌 Total listening ports: $open_ports"

    # Check for WireGuard port
    if ss -uln | grep -q ":51820"; then
        write_report "✅ WireGuard port (51820) is listening"
    else
        write_report "❌ WireGuard port (51820) not listening"
        ((network_issues++))
    fi

    # Check IP forwarding
    if [[ $(cat /proc/sys/net/ipv4/ip_forward) == "1" ]]; then
        write_report "✅ IP forwarding is enabled"
    else
        write_report "❌ IP forwarding is disabled"
        ((network_issues++))
    fi

    # Check for suspicious network connections
    local suspicious_connections=$(ss -tuln | grep -E ":(22|80|443|8080|8443)" | wc -l)
    write_report "🌐 Common service ports listening: $suspicious_connections"

    write_report ""
    write_report "Network Security Summary:"
    write_report "- Total network issues: $network_issues"

    return $network_issues
}

# Audit user and device management
audit_user_device_management() {
    write_report ""
    write_report "User and Device Management Audit"
    write_report "================================"

    local management_issues=0

    # Check device inventory
    local device_inventory="$PROJECT_ROOT/device-inventory.json"
    if [[ -f "$device_inventory" ]]; then
        local device_count=$(jq '.devices | length' "$device_inventory" 2>/dev/null || echo "0")
        write_report "📱 Total enrolled devices: $device_count"
        
        # Check for inactive devices
        local inactive_devices=$(jq -r '.devices[] | select(.status != "active") | .id' "$device_inventory" 2>/dev/null | wc -l)
        write_report "💤 Inactive devices: $inactive_devices"
        
        if [[ $inactive_devices -gt 0 ]]; then
            write_report "⚠️  Inactive devices found - consider cleanup"
        fi
    else
        write_report "❌ Device inventory file not found"
        ((management_issues++))
    fi

    # Check for orphaned certificates
    local cert_count=0
    local inventory_devices=0
    
    if [[ -d "$CERT_DIR/clients" ]]; then
        cert_count=$(find "$CERT_DIR/clients" -name "client.crt" | wc -l)
    fi
    
    if [[ -f "$device_inventory" ]]; then
        inventory_devices=$(jq '.devices | length' "$device_inventory" 2>/dev/null || echo "0")
    fi
    
    if [[ $cert_count -ne $inventory_devices ]]; then
        write_report "⚠️  Certificate count ($cert_count) doesn't match inventory ($inventory_devices)"
        ((management_issues++))
    else
        write_report "✅ Certificate count matches device inventory"
    fi

    write_report ""
    write_report "User and Device Management Summary:"
    write_report "- Total management issues: $management_issues"

    return $management_issues
}

# Audit log analysis and monitoring
audit_logs() {
    write_report ""
    write_report "Log Analysis and Monitoring Audit"
    write_report "================================="

    local log_issues=0

    # Check for authentication logs
    if [[ -f "/var/log/auth.log" ]]; then
        write_report "✅ Authentication log file found"
        
        # Check for recent failed login attempts
        local failed_logins=$(grep "Failed password" /var/log/auth.log | grep "$(date +%Y-%m-%d)" | wc -l)
        write_report "🔐 Failed login attempts today: $failed_logins"
        
        if [[ $failed_logins -gt $MAX_FAILED_LOGINS ]]; then
            write_report "⚠️  High number of failed login attempts detected"
            ((log_issues++))
        fi
    else
        write_report "❌ Authentication log file not found"
        ((log_issues++))
    fi

    # Check WireGuard logs
    if journalctl -u wg-quick@wg0 --since "24 hours ago" --quiet; then
        write_report "✅ WireGuard logs accessible"
        
        local wg_errors=$(journalctl -u wg-quick@wg0 --since "24 hours ago" --grep "error\|failed" | wc -l)
        write_report "🔧 WireGuard errors in last 24h: $wg_errors"
        
        if [[ $wg_errors -gt 0 ]]; then
            write_report "⚠️  WireGuard errors detected in recent logs"
            ((log_issues++))
        fi
    else
        write_report "❌ Cannot access WireGuard logs"
        ((log_issues++))
    fi

    # Check Authelia logs if available
    if journalctl -u authelia --since "24 hours ago" --quiet 2>/dev/null; then
        write_report "✅ Authelia logs accessible"
        
        local auth_failures=$(journalctl -u authelia --since "24 hours ago" --grep "authentication.*failed" | wc -l)
        write_report "🚫 Authentication failures in last 24h: $auth_failures"
        
        if [[ $auth_failures -gt $MAX_FAILED_LOGINS ]]; then
            write_report "⚠️  High number of authentication failures"
            ((log_issues++))
        fi
    else
        write_report "ℹ️  Authelia logs not accessible (service may not be running)"
    fi

    write_report ""
    write_report "Log Analysis Summary:"
    write_report "- Total log issues: $log_issues"

    return $log_issues
}

# Check compliance with security standards
audit_compliance() {
    write_report ""
    write_report "Security Compliance Audit"
    write_report "========================="

    local compliance_issues=0

    # Check encryption standards
    write_report "Encryption Standards:"
    
    # Check certificate key sizes
    if [[ -f "$CERT_DIR/ca/ca.crt" ]]; then
        local ca_key_size=$(openssl x509 -in "$CERT_DIR/ca/ca.crt" -noout -text | grep "Public-Key:" | grep -o "[0-9]*" | head -1)
        if [[ $ca_key_size -ge 2048 ]]; then
            write_report "✅ CA certificate uses adequate key size ($ca_key_size bits)"
        else
            write_report "❌ CA certificate uses inadequate key size ($ca_key_size bits)"
            ((compliance_issues++))
        fi
    fi

    # Check WireGuard configuration security
    local wg_config="/etc/wireguard/wg0.conf"
    if [[ -f "$wg_config" ]]; then
        if grep -q "PresharedKey" "$wg_config"; then
            write_report "✅ WireGuard uses pre-shared keys for additional security"
        else
            write_report "⚠️  WireGuard not using pre-shared keys"
            ((compliance_issues++))
        fi
    fi

    # Check password policies
    write_report ""
    write_report "Password Policy Compliance:"
    
    # This is a simplified check - in practice, you'd check actual password policies
    write_report "ℹ️  Manual review required for password policy compliance"

    # Check access control principles
    write_report ""
    write_report "Zero Trust Principles:"
    write_report "✅ Network segmentation implemented (WireGuard)"
    write_report "✅ Multi-factor authentication available (Authelia)"
    write_report "✅ Certificate-based device authentication"
    write_report "✅ Encrypted communications (WireGuard + TLS)"

    write_report ""
    write_report "Compliance Summary:"
    write_report "- Total compliance issues: $compliance_issues"

    return $compliance_issues
}

# Generate audit summary
generate_summary() {
    local total_issues=$1

    write_report ""
    write_report "AUDIT SUMMARY"
    write_report "============="
    write_report ""
    write_report "Audit completed at: $(date)"
    write_report "Total security issues found: $total_issues"
    write_report ""

    if [[ $total_issues -eq 0 ]]; then
        write_report "🎉 No critical security issues detected!"
        write_report "✅ Zero Trust VPN infrastructure appears to be secure"
    elif [[ $total_issues -le 5 ]]; then
        write_report "⚠️  Minor security issues detected"
        write_report "📝 Review and address the issues listed above"
    else
        write_report "❌ Multiple security issues detected"
        write_report "🚨 Immediate attention required to address security concerns"
    fi

    write_report ""
    write_report "Next recommended actions:"
    write_report "1. Review all flagged issues in detail"
    write_report "2. Update certificates nearing expiration"
    write_report "3. Review and update access control policies"
    write_report "4. Monitor logs for suspicious activity"
    write_report "5. Schedule regular security audits"
    write_report ""
    write_report "Report saved to: $REPORT_FILE"
}

# Main audit execution
main() {
    init_audit

    log "Starting $AUDIT_TYPE security audit..."

    local total_issues=0

    case "$AUDIT_TYPE" in
        "full")
            audit_certificates && total_issues=$((total_issues + $?))
            audit_access_control && total_issues=$((total_issues + $?))
            audit_network && total_issues=$((total_issues + $?))
            audit_user_device_management && total_issues=$((total_issues + $?))
            audit_logs && total_issues=$((total_issues + $?))
            audit_compliance && total_issues=$((total_issues + $?))
            ;;
        "quick")
            audit_certificates && total_issues=$((total_issues + $?))
            audit_network && total_issues=$((total_issues + $?))
            ;;
        "certificates")
            audit_certificates && total_issues=$((total_issues + $?))
            ;;
        "access-control")
            audit_access_control && total_issues=$((total_issues + $?))
            ;;
        "network")
            audit_network && total_issues=$((total_issues + $?))
            ;;
        "compliance")
            audit_compliance && total_issues=$((total_issues + $?))
            ;;
    esac

    generate_summary $total_issues

    if [[ "$REPORT_ONLY" != "true" ]]; then
        log "Security audit completed. Report saved to: $REPORT_FILE"
        
        if [[ $total_issues -gt 0 ]]; then
            warn "Security issues detected. Review the report for details."
            exit 1
        else
            log "No critical security issues found."
        fi
    fi
}

# Parse arguments and run main function
parse_args "$@"
main