# shellcheck shell=bash
# PKI helpers around "openssl ca". Sourced by common.sh.
#
# Layout under $PKI_DIR:
#   ca/ca.crt  ca/private/ca.key (encrypted with $PKI_CA_PASSFILE)
#   ca/openssl.cnf ca/index.txt ca/serial ca/crlnumber ca/newcerts/
#   server/<name>.key|crt   clients/<name>.key|crt   crl/ca.crl
#
# Every certificate goes through "openssl ca", so index.txt is the complete
# record of what was issued and the CRL can revoke anything.

_pki_passin() {
    if [[ -f "$PKI_CA_PASSFILE" ]]; then
        printf -- '-passin\nfile:%s\n' "$PKI_CA_PASSFILE"
    fi
}

_pki_genkey() {
    local alg="$1" out="$2"
    (
        umask 077
        case "$alg" in
            ec:*)  openssl genpkey -algorithm EC -pkeyopt "ec_paramgen_curve:${alg#ec:}" -out "$out" ;;
            rsa:*) openssl genpkey -algorithm RSA -pkeyopt "rsa_keygen_bits:${alg#rsa:}" -out "$out" ;;
            *) error "Unsupported key algorithm: $alg"; exit 1 ;;
        esac
    )
}

pki_write_ca_config() {
    local crl_ext=""
    if [[ -n "$PKI_CRL_URL" ]]; then
        crl_ext="crlDistributionPoints = URI:$PKI_CRL_URL"
    fi
    atomic_write "$PKI_CA_CNF" 644 <<EOF
# Generated by scripts/lib/pki.sh. Edit PKI_* settings in ztvpn.conf and
# re-run pki-setup.sh --write-config instead of editing this file.

[ ca ]
default_ca = CA_default

[ CA_default ]
dir               = $PKI_CA_DIR
database          = \$dir/index.txt
new_certs_dir     = \$dir/newcerts
serial            = \$dir/serial
crlnumber         = \$dir/crlnumber
certificate       = $PKI_CA_CERT
private_key       = $PKI_CA_KEY
crl               = $PKI_CRL
default_md        = sha256
default_days      = $PKI_CERT_DAYS
default_crl_days  = 30
preserve          = no
copy_extensions   = none
unique_subject    = no
policy            = policy_ztvpn
email_in_dn       = no
name_opt          = ca_default
cert_opt          = ca_default

[ policy_ztvpn ]
countryName             = optional
organizationName        = optional
organizationalUnitName  = optional
commonName              = supplied
emailAddress            = optional

[ req ]
distinguished_name  = req_dn
string_mask         = utf8only
default_md          = sha256
prompt              = no

[ req_dn ]
CN = placeholder

[ v3_ca ]
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid:always
basicConstraints       = critical, CA:true, pathlen:0
keyUsage               = critical, keyCertSign, cRLSign

[ server_cert ]
basicConstraints       = critical, CA:false
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid, issuer
keyUsage               = critical, digitalSignature, keyEncipherment
extendedKeyUsage       = serverAuth
$crl_ext

[ client_cert ]
basicConstraints       = critical, CA:false
subjectKeyIdentifier   = hash
authorityKeyIdentifier = keyid, issuer
keyUsage               = critical, digitalSignature
extendedKeyUsage       = clientAuth
$crl_ext

[ crl_ext ]
authorityKeyIdentifier = keyid:always
EOF
}

pki_ca_exists() {
    [[ -f "$PKI_CA_CERT" && -f "$PKI_CA_KEY" ]]
}

# Creates the CA. Refuses to touch an existing one.
pki_init_ca() {
    local cn="${1:-$PKI_ORG Root CA}"
    if pki_ca_exists; then
        error "CA already exists at $PKI_CA_DIR; refusing to overwrite"
        return 1
    fi
    (
        umask 077
        mkdir -p "$PKI_CA_DIR/private" "$PKI_CA_DIR/newcerts" "$PKI_SERVER_DIR" "$PKI_CLIENTS_DIR" \
            "$(dirname "$PKI_CRL")" "$(dirname "$PKI_CA_PASSFILE")"
    ) || return 1
    chmod 755 "$PKI_DIR" "$PKI_CA_DIR" "$PKI_CA_DIR/newcerts" "$(dirname "$PKI_CRL")"
    chmod 700 "$PKI_CA_DIR/private" "$PKI_CLIENTS_DIR" "$PKI_SERVER_DIR"
    : >"$PKI_CA_DIR/index.txt"
    printf 'unique_subject = no\n' >"$PKI_CA_DIR/index.txt.attr"
    openssl rand -hex 16 >"$PKI_CA_DIR/serial"
    printf '1000\n' >"$PKI_CA_DIR/crlnumber"
    pki_write_ca_config

    if [[ ! -f "$PKI_CA_PASSFILE" ]]; then
        (umask 077; gen_password 48 >"$PKI_CA_PASSFILE")
    fi

    local tmpkey
    tmpkey="$(mktemp "$PKI_CA_DIR/private/.ca.XXXXXX")"
    _pki_genkey "$PKI_CA_KEY_ALG" "$tmpkey" || { rm -f "$tmpkey"; return 1; }
    (umask 077; openssl pkey -in "$tmpkey" -aes256 -passout "file:$PKI_CA_PASSFILE" -out "$PKI_CA_KEY")
    rm -f "$tmpkey"
    chmod 400 "$PKI_CA_KEY"

    local subj="/CN=$cn/O=$PKI_ORG"
    [[ -n "$PKI_COUNTRY" ]] && subj="/C=$PKI_COUNTRY$subj"
    openssl req -config "$PKI_CA_CNF" -new -x509 -extensions v3_ca \
        -key "$PKI_CA_KEY" -passin "file:$PKI_CA_PASSFILE" \
        -days "$PKI_CA_DAYS" -subj "$subj" -out "$PKI_CA_CERT"
    chmod 644 "$PKI_CA_CERT"
    pki_gen_crl
}

_pki_subject() {
    local cn="$1" subj
    subj="/CN=$cn/O=$PKI_ORG"
    [[ -n "$PKI_COUNTRY" ]] && subj="/C=$PKI_COUNTRY$subj"
    printf '%s\n' "$subj"
}

# pki_issue <server|client> <name> [days] [dns-or-ip SAN ...]
# Writes <dir>/<name>.key and <dir>/<name>.crt, prints the cert path.
pki_issue() {
    local kind="$1" name="$2" days="${3:-$PKI_CERT_DAYS}"
    shift 3 2>/dev/null || shift $#
    local dir section
    case "$kind" in
        server) dir="$PKI_SERVER_DIR"; section=server_cert ;;
        client) dir="$PKI_CLIENTS_DIR"; section=client_cert ;;
        *) error "Unknown certificate kind: $kind"; return 1 ;;
    esac
    [[ "$name" =~ ^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$ ]] || { error "Invalid certificate name: $name"; return 1; }
    [[ "$days" =~ ^[0-9]+$ ]] || { error "Invalid validity: $days"; return 1; }
    pki_ca_exists || { error "No CA at $PKI_CA_DIR, run pki-setup.sh first"; return 1; }
    mkdir -p "$dir"

    local work rc=0
    work="$(mktemp -d)"
    _pki_issue_in "$kind" "$name" "$days" "$dir" "$section" "$work" "$@" || rc=$?
    rm -rf "$work"
    return "$rc"
}

_pki_issue_in() {
    local kind="$1" name="$2" days="$3" dir="$4" section="$5" work="$6"
    shift 6

    _pki_genkey "$PKI_KEY_ALG" "$work/key.pem" || return 1
    openssl req -config "$PKI_CA_CNF" -new -key "$work/key.pem" \
        -subj "$(_pki_subject "$name")" -out "$work/req.csr" || return 1

    local extfile="$work/ext.cnf" san="" s
    {
        printf '[ %s ]\n' "$section"
        awk -v s="[ $section ]" '
            $0 == s { on = 1; next }
            /^\[/ { on = 0 }
            on && NF { print }
        ' "$PKI_CA_CNF"
        if [[ "$kind" == server ]]; then
            san="DNS:$name"
            for s in "$@"; do
                if validate_ipv4 "$s"; then
                    san+=",IP:$s"
                elif [[ "$s" =~ ^(\*\.)?[A-Za-z0-9]([A-Za-z0-9-]{0,62})(\.[A-Za-z0-9-]{1,63})*$ ]]; then
                    san+=",DNS:$s"
                else
                    error "Invalid SAN: $s"
                    return 1
                fi
            done
            printf 'subjectAltName = %s\n' "$san"
        fi
    } >"$extfile" || return 1

    local -a passin
    mapfile -t passin < <(_pki_passin)
    openssl ca -batch -config "$PKI_CA_CNF" "${passin[@]}" \
        -extfile "$extfile" -extensions "$section" -days "$days" \
        -in "$work/req.csr" -out "$work/cert.pem" -notext || return 1

    install -m 600 "$work/key.pem" "$dir/$name.key"
    install -m 644 "$work/cert.pem" "$dir/$name.crt"
    printf '%s\n' "$dir/$name.crt"
}

# Prints serials of all valid (not revoked, not expired) certs with CN=name.
pki_valid_serials() {
    local name="$1"
    [[ -f "$PKI_CA_DIR/index.txt" ]] || return 0
    awk -F'\t' -v cn="$name" '
        $1 == "V" {
            n = split($6, parts, "/")
            for (i = 1; i <= n; i++) if (parts[i] == "CN=" cn) { print $4; break }
        }
    ' "$PKI_CA_DIR/index.txt"
}

# Revokes every valid certificate whose CN is exactly <name>.
# pki_revoke <name> [reason]
pki_revoke() {
    local name="$1" reason="${2:-cessationOfOperation}" serial count=0
    case "$reason" in
        unspecified|keyCompromise|CACompromise|affiliationChanged|superseded|cessationOfOperation|certificateHold) ;;
        *) error "Invalid CRL reason: $reason"; return 1 ;;
    esac
    local -a passin
    mapfile -t passin < <(_pki_passin)
    while IFS= read -r serial; do
        [[ -n "$serial" ]] || continue
        openssl ca -config "$PKI_CA_CNF" "${passin[@]}" \
            -revoke "$PKI_CA_DIR/newcerts/$serial.pem" -crl_reason "$reason" || return 1
        count=$((count + 1))
    done < <(pki_valid_serials "$name")
    ((count > 0)) || return 2
    pki_gen_crl
}

pki_gen_crl() {
    local -a passin
    mapfile -t passin < <(_pki_passin)
    mkdir -p "$(dirname "$PKI_CRL")"
    openssl ca -config "$PKI_CA_CNF" "${passin[@]}" -gencrl -out "$PKI_CRL.tmp" &&
        chmod 644 "$PKI_CRL.tmp" && mv -f "$PKI_CRL.tmp" "$PKI_CRL"
}

# Seconds until the certificate expires (negative if expired).
pki_seconds_left() {
    local end
    end="$(openssl x509 -in "$1" -noout -enddate 2>/dev/null)" || return 1
    end="${end#notAfter=}"
    echo $(($(date -d "$end" +%s) - $(date +%s)))
}

pki_days_left() {
    local s
    s="$(pki_seconds_left "$1")" || return 1
    echo $((s / 86400))
}

# True if the cert is signed by our CA and not revoked according to the CRL.
pki_verify() {
    openssl verify -crl_check -CAfile <(cat "$PKI_CA_CERT" "$PKI_CRL") "$1" >/dev/null 2>&1
}
