# shellcheck shell=bash
# Reverse proxy (nginx in the compose stack) helpers. Sourced by common.sh.
#
# Mutual TLS is opt-in (MTLS=yes in ztvpn.conf). initial-setup.sh renders
# $CONFIG_PATH/nginx/snippets/mtls.conf with mtls_snippet on every run, and
# every HTTPS server block of the nginx templates includes it. The compose
# file mounts the CA certificate (a single file, never the ca/ directory
# with private/ca.key) and the crl/ directory into the container.

# Where docker-compose.yml mounts the CA certificate and the CRL directory.
MTLS_NGINX_CA="/etc/nginx/client-ca/ca.crt"
MTLS_NGINX_CRL="/etc/nginx/crl/ca.crl"

validate_yes_no() {
    [[ "$1" == yes || "$1" == no ]]
}

# mtls_snippet <yes|no>: prints the content of snippets/mtls.conf.
mtls_snippet() {
    local mode="$1"
    validate_yes_no "$mode" || { error "MTLS must be yes or no, not '$mode'"; return 1; }
    cat <<EOF
# Generated by scripts/setup/initial-setup.sh from MTLS=$mode in ztvpn.conf.
# Rewritten on every run: change MTLS there, not this file.
# Included in every HTTPS server block, including the default server that
# rejects unknown names (not in the port 80 redirect/healthz server).
EOF
    if [[ "$mode" == no ]]; then
        cat <<'EOF'
#
# MTLS=no: client certificates are NOT requested or checked. Access to the
# portal and the applications needs only the Authelia login.
EOF
        return 0
    fi
    cat <<EOF
#
# MTLS=yes: every request needs a client certificate issued by the
# zero-trust-vpn CA that is not on its CRL. Clients import the .p12 bundle
# from add-user.sh / device-enrollment.sh --cert.
#
# nginx reads the CRL at start and reload only, and rejects EVERY client
# once its nextUpdate has passed. The scripts reload nginx after each CRL
# change; run "cert-renewal.sh renew" daily so the CRL never runs out.
ssl_client_certificate $MTLS_NGINX_CA;
ssl_crl                $MTLS_NGINX_CRL;
ssl_verify_client      on;
ssl_verify_depth       1;

# No TLS session resumption: a resumed session skips certificate
# verification, so a revoked certificate would keep working until its
# session expired. nginx looks sessions up in the default server's cache,
# which is why default.conf includes this file in that server as well.
ssl_session_cache      off;

# 496: no certificate sent, 495: certificate did not verify (unknown CA,
# revoked, expired). Answer with a plain explanation instead of nginx's
# generic "400 Bad Request" page.
error_page 496 = @ztvpn_mtls_missing;
error_page 495 = @ztvpn_mtls_invalid;

location @ztvpn_mtls_missing {
    default_type text/plain;
    return 403 "Client certificate required: import the .p12 bundle from your onboarding into this browser or device.\\n";
}

location @ztvpn_mtls_invalid {
    default_type text/plain;
    return 403 "Client certificate rejected (\$ssl_client_verify): it is revoked, expired or not issued by this VPN.\\n";
}
EOF
}

# Prints every nginx template/config in <dir> whose TLS server blocks do
# not all include snippets/mtls.conf (count of "listen ... 443" lines vs.
# includes, comments ignored). With MTLS=yes such a server would accept
# requests without a client certificate.
mtls_unprotected_templates() {
    local dir="$1" f
    for f in "$dir"/*.template "$dir"/*.conf; do
        [[ -f "$f" ]] || continue
        awk '
            { sub(/#.*/, "") }
            /^[[:space:]]*listen[[:space:]][^;]*443/ { tls++ }
            /^[[:space:]]*include[[:space:]]+\/etc\/nginx\/snippets\/mtls\.conf[[:space:]]*;/ { inc++ }
            END { exit !(tls > inc) }
        ' "$f" && printf '%s\n' "$f"
    done
    return 0
}

# Reloads the TLS proxy (nginx re-reads certificates, CRL and config) with
# SIGHUP: the compose service $TLS_PROXY_SERVICE, or TLS_PROXY_CONTAINER if
# set. A proxy that is not running is left alone (it loads everything on
# start). Returns 1 if a running proxy could not be signalled or there is
# no way to reach it; never exits.
tls_proxy_reload() {
    if [[ -n "$TLS_PROXY_CONTAINER" && ! "$TLS_PROXY_CONTAINER" =~ ^[A-Za-z0-9][A-Za-z0-9_.-]*$ ]]; then
        error "Invalid TLS_PROXY_CONTAINER: $TLS_PROXY_CONTAINER"
        return 1
    fi
    if [[ ! "$TLS_PROXY_SERVICE" =~ ^[A-Za-z0-9][A-Za-z0-9_.-]*$ ]]; then
        error "Invalid TLS_PROXY_SERVICE: $TLS_PROXY_SERVICE"
        return 1
    fi
    if ! command -v docker >/dev/null 2>&1; then
        warn "docker not found; reload the TLS proxy manually"
        return 1
    fi
    local running target
    local -a kill_cmd
    if [[ -n "$TLS_PROXY_CONTAINER" ]]; then
        target="container $TLS_PROXY_CONTAINER"
        running="$(docker inspect -f '{{.State.Running}}' "$TLS_PROXY_CONTAINER" 2>/dev/null || true)"
        [[ "$running" == true ]] || running=""
        kill_cmd=(docker kill -s SIGHUP "$TLS_PROXY_CONTAINER")
    elif [[ -f "$COMPOSE_FILE_PATH" ]]; then
        target="compose service $TLS_PROXY_SERVICE"
        local -a compose=(docker compose -f "$COMPOSE_FILE_PATH" --project-directory "$(dirname "$COMPOSE_FILE_PATH")")
        running="$("${compose[@]}" ps -q --status running "$TLS_PROXY_SERVICE" 2>/dev/null || true)"
        kill_cmd=("${compose[@]}" kill -s SIGHUP "$TLS_PROXY_SERVICE")
    else
        warn "No $COMPOSE_FILE_PATH and no TLS_PROXY_CONTAINER set; reload the TLS proxy manually"
        return 1
    fi
    if [[ -z "$running" ]]; then
        info "The $target is not running; it loads the current certificates and CRL on start"
        return 0
    fi
    if "${kill_cmd[@]}" >/dev/null; then
        success "Sent SIGHUP (reload) to the $target"
    else
        error "Could not reload the $target; reload it manually"
        return 1
    fi
}

# Called by pki_gen_crl after a new CRL was written. With MTLS=yes nginx
# only enforces the new CRL (and the new nextUpdate) after a reload.
# No-op when MTLS is not yes, when PKI_CRL_RELOAD=no (the caller reloads
# itself) or when there is no proxy deployment on this host. Never fails.
proxy_crl_changed() {
    [[ "${MTLS:-no}" == yes && "${PKI_CRL_RELOAD:-yes}" != no ]] || return 0
    [[ -n "$TLS_PROXY_CONTAINER" || -f "$COMPOSE_FILE_PATH" ]] || return 0
    tls_proxy_reload ||
        warn "CRL updated, but nginx still enforces the previous one until it is reloaded"
    return 0
}
